version: '0.1'

services:
  ds:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080

  postgres-db:
    build:
      context: .
      dockerfile: postgres.dockerfile
    environment:
      DATABASE_URL: postgres:://username:password@localhost/holocron
    ports:
      - "5432:5432"  # Map container port 5432 to host port 5432

